SELECT E.ID, E.GENOTYPE, E2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA E JOIN ECOLI_DATA E2 ON E.PARENT_ID=E2.ID
WHERE E.PARENT_ID IS NOT NULL 
  AND E.GENOTYPE & E2.GENOTYPE = E2.GENOTYPE
  ORDER BY E.ID